"""change Member.mythic_inventory to be Array, not Dict

Revision ID: 22cae99ca4c3
Revises: 388c94587b63
Create Date: 2026-03-17 18:00:09.794231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cae99ca4c3'
down_revision: Union[str, Sequence[str], None] = '388c94587b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
