"""add Mythic Prisms and Mythic Inventory

Revision ID: 388c94587b63
Revises: 9ab162c4dc13
Create Date: 2026-03-17 12:57:34.071898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388c94587b63'
down_revision: Union[str, Sequence[str], None] = '9ab162c4dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Member', sa.Column('spent_prisms', sa.Integer(), nullable=True))
    op.add_column('Member', sa.Column('mythic_inventory', sa.JSON(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('server', sa.Column('mythic_prism_roles', sa.JSON(), server_default=sa.text("'{}'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'mythic_prism_roles')
    op.drop_column('Member', 'mythic_inventory')
    op.drop_column('Member', 'spent_prisms')
    # ### end Alembic commands ###
