"""rename MemberLevel table to Member

Revision ID: 9ab162c4dc13
Revises: cbf61c4ebc8d
Create Date: 2026-03-16 19:12:29.725927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab162c4dc13'
down_revision: Union[str, Sequence[str], None] = 'cbf61c4ebc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Member',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('vc_time', sa.Float(), nullable=False),
    sa.Column('in_vc', sa.Boolean(), nullable=False),
    sa.Column('last_vc_join', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_message_xp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_vc_xp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'id')
    )
    op.drop_table('memberlevel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberlevel',
    sa.Column('guild_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('xp', sa.INTEGER(), nullable=False),
    sa.Column('vc_time', sa.FLOAT(), nullable=False),
    sa.Column('next_message_xp', sa.DATETIME(), nullable=False),
    sa.Column('next_vc_xp', sa.DATETIME(), nullable=False),
    sa.Column('in_vc', sa.BOOLEAN(), nullable=False),
    sa.Column('last_vc_join', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'id')
    )
    op.drop_table('Member')
    # ### end Alembic commands ###
