name: deploy bot to main server (hosted under https://yip.cat)
on:
  push:
    branches: [ main ]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Execute remote SSH commands using SSH key
            uses: appleboy/ssh-action@v1
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: ./bot-deploy.sh